export const COLLECTION_COPY = Object.freeze({
  en:{eyebrow:'YOUR COLLECTION',title:'Collection',intro:'Browse the current Wand Database through user-facing families, worlds and universes.',category:'Category',world:'World',universe:'Universe',search:'Search all official names',all:'All',results:'results',showing:'showing',loading:'Loading verified v1.25 data…',failed:'Collection data could not be verified.',media:'Images are intentionally withheld until current v1.25 media bytes and public-display rights are approved.',personal:'Personal Progress',personalDetail:'Load a supported DDV save to add Owned / Missing / Discovered and family-specific personal state. This browse surface does not invent personal state.',trackable:'Trackable',readonly:'Reference only',source:'Nintendo Switch · DDV v1.25.0',more:'Refine the search or facet to narrow the result set.',empty:'No matching Collection entries.',itemId:'Item ID'},
  fr:{eyebrow:'VOTRE COLLECTION',title:'Collection',intro:'Parcourez la base Wand actuelle par familles, mondes et univers.',category:'Catégorie',world:'Monde',universe:'Univers',search:'Rechercher dans tous les noms officiels',all:'Tous',results:'résultats',showing:'affichés',loading:'Chargement des données v1.25 vérifiées…',failed:'Les données Collection n’ont pas pu être vérifiées.',media:'Les images restent masquées tant que les fichiers média v1.25 actuels et les droits d’affichage public ne sont pas approuvés.',personal:'Progression personnelle',personalDetail:'Chargez une sauvegarde DDV compatible pour ajouter Possédé / Manquant / Découvert et les états propres à chaque famille. Cette vue n’invente aucun état personnel.',trackable:'Suivable',readonly:'Référence seule',source:'Nintendo Switch · DDV v1.25.0',more:'Affinez la recherche ou le filtre pour réduire les résultats.',empty:'Aucune entrée correspondante.',itemId:'ID objet'},
  it:{eyebrow:'LA TUA COLLEZIONE',title:'Collection',intro:'Esplora il Database Wand corrente tramite famiglie, mondi e universi orientati all’utente.',category:'Categoria',world:'Mondo',universe:'Universo',search:'Cerca in tutti i nomi ufficiali',all:'Tutti',results:'risultati',showing:'mostrati',loading:'Caricamento dei dati v1.25 verificati…',failed:'Impossibile verificare i dati Collection.',media:'Le immagini restano nascoste finché i byte media v1.25 correnti e i diritti di visualizzazione pubblica non sono approvati.',personal:'Progresso personale',personalDetail:'Carica un salvataggio DDV supportato per aggiungere Posseduto / Mancante / Scoperto e gli stati specifici della famiglia. Questa vista non inventa stati personali.',trackable:'Tracciabile',readonly:'Solo riferimento',source:'Nintendo Switch · DDV v1.25.0',more:'Affina la ricerca o il filtro per ridurre i risultati.',empty:'Nessuna voce corrispondente.',itemId:'ID oggetto'},
  de:{eyebrow:'DEINE SAMMLUNG',title:'Collection',intro:'Durchsuche die aktuelle Wand-Datenbank nach benutzerorientierten Familien, Welten und Universen.',category:'Kategorie',world:'Welt',universe:'Universum',search:'Alle offiziellen Namen durchsuchen',all:'Alle',results:'Ergebnisse',showing:'angezeigt',loading:'Verifizierte v1.25-Daten werden geladen…',failed:'Collection-Daten konnten nicht verifiziert werden.',media:'Bilder bleiben ausgeblendet, bis aktuelle v1.25-Mediendateien und öffentliche Anzeigerechte bestätigt sind.',personal:'Persönlicher Fortschritt',personalDetail:'Lade einen unterstützten DDV-Spielstand, um Besessen / Fehlend / Entdeckt und familienspezifische Zustände hinzuzufügen. Diese Ansicht erfindet keinen persönlichen Status.',trackable:'Verfolgbar',readonly:'Nur Referenz',source:'Nintendo Switch · DDV v1.25.0',more:'Verfeinere Suche oder Filter, um die Ergebnisse einzugrenzen.',empty:'Keine passenden Einträge.',itemId:'Item-ID'},
  'es-ES':{eyebrow:'TU COLECCIÓN',title:'Collection',intro:'Explora la base de datos actual de Wand mediante familias, mundos y universos orientados al usuario.',category:'Categoría',world:'Mundo',universe:'Universo',search:'Buscar en todos los nombres oficiales',all:'Todos',results:'resultados',showing:'mostrados',loading:'Cargando datos v1.25 verificados…',failed:'No se pudieron verificar los datos de Collection.',media:'Las imágenes se mantienen ocultas hasta aprobar los archivos multimedia actuales de v1.25 y los derechos de visualización pública.',personal:'Progreso personal',personalDetail:'Carga una partida DDV compatible para añadir Poseído / Falta / Descubierto y estados específicos de cada familia. Esta vista no inventa estado personal.',trackable:'Rastreable',readonly:'Solo referencia',source:'Nintendo Switch · DDV v1.25.0',more:'Refina la búsqueda o el filtro para reducir los resultados.',empty:'No hay entradas coincidentes.',itemId:'ID de objeto'},
  ja:{eyebrow:'あなたのコレクション',title:'Collection',intro:'現在のWand Databaseを、ユーザー向けのCategory・World・Universeから横断して探します。',category:'Category',world:'World',universe:'Universe',search:'8言語の公式名を検索',all:'すべて',results:'件',showing:'表示',loading:'検証済みv1.25データを読み込み中…',failed:'Collectionデータを検証できませんでした。',media:'現行v1.25のmedia byte検証とpublic-display rights承認が完了するまで、画像は意図的に表示しません。',personal:'Personal Progress',personalDetail:'対応DDVセーブを読み込むと、Owned / Missing / Discoveredやfamily固有の個人状態を重ねられます。このbrowse画面では個人状態を推測しません。',trackable:'追跡対応',readonly:'参照のみ',source:'Nintendo Switch · DDV v1.25.0',more:'検索またはfacetを絞ると、さらに結果を限定できます。',empty:'一致するCollection項目がありません。',itemId:'Item ID'},
  'zh-CN':{eyebrow:'你的收藏',title:'Collection',intro:'通过面向用户的类别、世界和宇宙浏览当前 Wand Database。',category:'类别',world:'世界',universe:'宇宙',search:'搜索全部 8 种官方语言名称',all:'全部',results:'项结果',showing:'显示',loading:'正在加载已验证的 v1.25 数据…',failed:'无法验证 Collection 数据。',media:'在当前 v1.25 媒体字节和公开展示权获得批准前，图片会保持隐藏。',personal:'个人进度',personalDetail:'载入受支持的 DDV 存档后可叠加已拥有 / 缺少 / 已发现及各类别专属状态。本浏览界面不会推测个人状态。',trackable:'可追踪',readonly:'仅参考',source:'Nintendo Switch · DDV v1.25.0',more:'缩小搜索或筛选条件可进一步减少结果。',empty:'没有匹配的 Collection 条目。',itemId:'物品 ID'},
  'pt-BR':{eyebrow:'SUA COLEÇÃO',title:'Collection',intro:'Explore o Wand Database atual por famílias, mundos e universos voltados ao usuário.',category:'Categoria',world:'Mundo',universe:'Universo',search:'Pesquisar todos os nomes oficiais',all:'Todos',results:'resultados',showing:'exibidos',loading:'Carregando dados v1.25 verificados…',failed:'Não foi possível verificar os dados da Collection.',media:'As imagens permanecem ocultas até que os bytes de mídia v1.25 atuais e os direitos de exibição pública sejam aprovados.',personal:'Progresso pessoal',personalDetail:'Carregue um save DDV compatível para adicionar Possuído / Ausente / Descoberto e estados específicos de cada família. Esta tela não inventa estado pessoal.',trackable:'Rastreável',readonly:'Somente referência',source:'Nintendo Switch · DDV v1.25.0',more:'Refine a busca ou o filtro para reduzir os resultados.',empty:'Nenhuma entrada correspondente.',itemId:'ID do item'}
});
export function collectionCopy(locale){return COLLECTION_COPY[locale]??COLLECTION_COPY.en;}


const COLLECTION_FAMILY_LABELS = Object.freeze({
  en:{
    'Appearance':'Appearance','Board Game':'Board Game','Buildings':'Buildings','Characters':'Characters','Clothing':'Clothing','Companions':'Companions','Crafting':'Crafting','Critters':'Critters','Environment Effects':'Environment Effects','Fish':'Fish','Foraging':'Foraging','Furniture':'Furniture','Gems':'Gems','Ingredients':'Ingredients','Landscaping':'Landscaping','Lorekeeper Tales':'Lorekeeper Tales','Meals':'Meals','Mounts':'Mounts','Photo Mode':'Photo Mode','Roads & Fences':'Roads & Fences','Snippets':'Snippets','Timebending':'Timebending','Tools':'Tools','Touch of Magic':'Touch of Magic','Upgrades':'Upgrades','Wallpaper & Flooring':'Wallpaper & Flooring'
  },
  fr:{
    'Appearance':'Apparence','Board Game':'Jeu de plateau','Buildings':'Bâtiments','Characters':'Personnages','Clothing':'Vêtements','Companions':'Compagnons','Crafting':'Fabrication','Critters':'Bestioles','Environment Effects':'Effets d’environnement','Fish':'Poissons','Foraging':'Cueillette','Furniture':'Meubles','Gems':'Gemmes','Ingredients':'Ingrédients','Landscaping':'Aménagement paysager','Lorekeeper Tales':'Contes du Gardien du savoir','Meals':'Repas','Mounts':'Montures','Photo Mode':'Mode photo','Roads & Fences':'Routes et clôtures','Snippets':'Fragments','Timebending':'Timebending','Tools':'Outils','Touch of Magic':'Touch of Magic','Upgrades':'Améliorations','Wallpaper & Flooring':'Papier peint et sols'
  },
  it:{
    'Appearance':'Aspetto','Board Game':'Gioco da tavolo','Buildings':'Edifici','Characters':'Personaggi','Clothing':'Abbigliamento','Companions':'Compagni','Crafting':'Creazione','Critters':'Animaletti','Environment Effects':'Effetti ambientali','Fish':'Pesci','Foraging':'Raccolta','Furniture':'Mobili','Gems':'Gemme','Ingredients':'Ingredienti','Landscaping':'Paesaggistica','Lorekeeper Tales':'Racconti del Custode del sapere','Meals':'Pasti','Mounts':'Cavalcature','Photo Mode':'Modalità foto','Roads & Fences':'Strade e recinzioni','Snippets':'Frammenti','Timebending':'Timebending','Tools':'Strumenti','Touch of Magic':'Touch of Magic','Upgrades':'Potenziamenti','Wallpaper & Flooring':'Carta da parati e pavimenti'
  },
  de:{
    'Appearance':'Aussehen','Board Game':'Brettspiel','Buildings':'Gebäude','Characters':'Charaktere','Clothing':'Kleidung','Companions':'Begleiter','Crafting':'Herstellung','Critters':'Kleintiere','Environment Effects':'Umgebungseffekte','Fish':'Fische','Foraging':'Sammeln','Furniture':'Möbel','Gems':'Edelsteine','Ingredients':'Zutaten','Landscaping':'Landschaftsgestaltung','Lorekeeper Tales':'Geschichten des Wissenshüters','Meals':'Gerichte','Mounts':'Reittiere','Photo Mode':'Fotomodus','Roads & Fences':'Wege & Zäune','Snippets':'Schnipsel','Timebending':'Timebending','Tools':'Werkzeuge','Touch of Magic':'Touch of Magic','Upgrades':'Verbesserungen','Wallpaper & Flooring':'Tapeten & Böden'
  },
  'es-ES':{
    'Appearance':'Apariencia','Board Game':'Juego de mesa','Buildings':'Edificios','Characters':'Personajes','Clothing':'Ropa','Companions':'Compañeros','Crafting':'Fabricación','Critters':'Animalitos','Environment Effects':'Efectos ambientales','Fish':'Peces','Foraging':'Recolección','Furniture':'Muebles','Gems':'Gemas','Ingredients':'Ingredientes','Landscaping':'Paisajismo','Lorekeeper Tales':'Relatos del Guardián del saber','Meals':'Comidas','Mounts':'Monturas','Photo Mode':'Modo foto','Roads & Fences':'Caminos y vallas','Snippets':'Fragmentos','Timebending':'Timebending','Tools':'Herramientas','Touch of Magic':'Touch of Magic','Upgrades':'Mejoras','Wallpaper & Flooring':'Papel pintado y suelos'
  },
  ja:{
    'Appearance':'外見','Board Game':'ボードゲーム','Buildings':'建物','Characters':'キャラクター','Clothing':'衣装','Companions':'コンパニオン','Crafting':'クラフト','Critters':'小動物','Environment Effects':'環境エフェクト','Fish':'魚','Foraging':'採集','Furniture':'家具','Gems':'宝石','Ingredients':'食材','Landscaping':'景観','Lorekeeper Tales':'ロアキーパーの物語','Meals':'料理','Mounts':'乗り物','Photo Mode':'フォトモード','Roads & Fences':'道とフェンス','Snippets':'スニペット','Timebending':'タイムベンディング','Tools':'道具','Touch of Magic':'Touch of Magic','Upgrades':'アップグレード','Wallpaper & Flooring':'壁紙と床材'
  },
  'zh-CN':{
    'Appearance':'外观','Board Game':'桌游','Buildings':'建筑','Characters':'角色','Clothing':'服装','Companions':'伙伴','Crafting':'制作','Critters':'小动物','Environment Effects':'环境效果','Fish':'鱼','Foraging':'采集','Furniture':'家具','Gems':'宝石','Ingredients':'食材','Landscaping':'景观','Lorekeeper Tales':'知识守护者故事','Meals':'菜肴','Mounts':'坐骑','Photo Mode':'拍照模式','Roads & Fences':'道路与栅栏','Snippets':'片段','Timebending':'时光弯曲','Tools':'工具','Touch of Magic':'Touch of Magic','Upgrades':'升级','Wallpaper & Flooring':'壁纸与地板'
  },
  'pt-BR':{
    'Appearance':'Aparência','Board Game':'Jogo de tabuleiro','Buildings':'Edifícios','Characters':'Personagens','Clothing':'Roupas','Companions':'Companheiros','Crafting':'Fabricação','Critters':'Bichinhos','Environment Effects':'Efeitos ambientais','Fish':'Peixes','Foraging':'Coleta','Furniture':'Móveis','Gems':'Gemas','Ingredients':'Ingredientes','Landscaping':'Paisagismo','Lorekeeper Tales':'Contos do Guardião do conhecimento','Meals':'Refeições','Mounts':'Montarias','Photo Mode':'Modo Foto','Roads & Fences':'Caminhos e cercas','Snippets':'Fragmentos','Timebending':'Timebending','Tools':'Ferramentas','Touch of Magic':'Touch of Magic','Upgrades':'Melhorias','Wallpaper & Flooring':'Papéis de parede e pisos'
  }
});

export function collectionFamilyLabel(locale, family) {
  return COLLECTION_FAMILY_LABELS[locale]?.[family] ?? COLLECTION_FAMILY_LABELS.en[family] ?? family;
}
