import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const loc=require('../src/lib/ddv/core/world/location-v125.js');
const audit=JSON.parse(fs.readFileSync(new URL('./fixtures/ddv-world/outdoor-location-routing-audit-v125.json',import.meta.url),'utf8'));
let passed=0;const t=(name,fn)=>{try{fn();passed++;console.log('PASS',name);}catch(e){console.error('FAIL',name,e);process.exitCode=1;}};
function profileFromAudit({gridOffset=0,reverseIds=false}={}){
 const FloatingIslands={},Grids={};
 for(const island of audit.floatingIslands){
  const roots=[];
  for(const r of island.directRoots){const gid=r.sourceGridId+gridOffset;roots.push(gid);Grids[String(gid)]={ID:gid,GridDataPath:r.gridDataPath,GridDefaultLayoutPath:'',TessellationFactor:r.tessellationFactor,Objects:{}};}
  if(reverseIds)roots.reverse();
  FloatingIslands[String(island.sceneItemId)]={SceneItemId:island.sceneItemId,GridIDs:roots,Unlocked:true,CustomLocationPositionsPath:island.customLocationPositionsPath,CharacterStates:{},EnvironmentEffectItemID:0,EnvironmentEffectOrientation:'GridOrientation_Up'};
 }
 return {World:{Villages:[],FloatingIslands,GridCollection:{Grids}}};
}
const base=profileFromAudit();

t('audit is current-v1.25 13 islands / 26 unique direct roots',()=>{assert.equal(audit.summary.floatingIslandCount,13);assert.equal(audit.summary.directRootCount,26);assert.equal(audit.summary.uniqueDirectGridDataPathCount,26);assert.equal(audit.summary.mapKeyEqualsSceneItemIdCount,13);assert.equal(audit.summary.crossSnapshotSemanticRouteParity,true);});
t('Floating Island public identity resolves by SceneItemId, not GridID',()=>{const r=loc.resolveFloatingIsland(base,1540000149);assert.equal(r.status,'RESOLVED');assert.deepEqual(r.locationRef,{codec:loc.LOCATION_CODEC,kind:'FLOATING_ISLAND',sceneItemId:1540000149});assert.equal(r.directRoots.length,4);assert.ok(r.directRoots.every(x=>typeof x.gridDataPath==='string'));});
t('same LocationRef survives complete destination GridID remap',()=>{const src=loc.resolveFloatingIsland(base,1540000193);const dest=profileFromAudit({gridOffset:50000,reverseIds:true});const dst=loc.resolveLocationRef(dest,src.locationRef);assert.equal(dst.status,'RESOLVED');assert.deepEqual(dst.locationRef,src.locationRef);assert.notDeepEqual(dst.directRoots.map(x=>x.sourceGridId),src.directRoots.map(x=>x.sourceGridId));assert.deepEqual(new Set(dst.directRoots.map(x=>x.gridDataPath)),new Set(src.directRoots.map(x=>x.gridDataPath)));});
t('multi-grid destination root resolves by exact GridDataPath after GridID/order remap',()=>{const src=loc.resolveFloatingIsland(base,1540000149);const route={codec:loc.DIRECT_GRID_ROUTE_CODEC,gridDataPath:src.directRoots[2].gridDataPath};const dest=profileFromAudit({gridOffset:90000,reverseIds:true});const r=loc.resolveDestinationDirectRoot(dest,src.locationRef,route);assert.equal(r.status,'RESOLVED');assert.equal(r.destinationGridId,src.directRoots[2].sourceGridId+90000);});
t('source GridID itself is not accepted as a direct-root route token',()=>{const r=loc.resolveDestinationDirectRoot(base,loc.locationRefFloatingIsland(1540000149),{codec:loc.DIRECT_GRID_ROUTE_CODEC,gridId:762});assert.equal(r.status,'INVALID');});
t('map-key / SceneItemId mismatch fails closed',()=>{const p=profileFromAudit();p.World.FloatingIslands['1540000147'].SceneItemId=1540000148;const r=loc.resolveFloatingIsland(p,1540000147);assert.equal(r.status,'AMBIGUOUS_FAIL_CLOSED');assert.equal(r.blockers[0].code,'FLOATING_ISLAND_MAP_KEY_VALUE_MISMATCH');});
t('duplicate direct GridDataPath fails closed instead of choosing an ordinal',()=>{const p=profileFromAudit();const fi=p.World.FloatingIslands['1540000149'];p.World.GridCollection.Grids[String(fi.GridIDs[1])].GridDataPath=p.World.GridCollection.Grids[String(fi.GridIDs[0])].GridDataPath;const r=loc.resolveFloatingIsland(p,1540000149);assert.equal(r.status,'AMBIGUOUS_FAIL_CLOSED');assert.equal(r.blockers[0].code,'LOCATION_DIRECT_GRID_PATH_DUPLICATE');});
t('missing exact destination GridDataPath fails closed',()=>{const dest=profileFromAudit({gridOffset:10000});const route={codec:loc.DIRECT_GRID_ROUTE_CODEC,gridDataPath:'GridData/FloatingIslands/Unknown.json'};const r=loc.resolveDestinationDirectRoot(dest,loc.locationRefFloatingIsland(1540000192),route);assert.equal(r.status,'NOT_FOUND');assert.equal(r.blockers[0].code,'DIRECT_GRID_ROUTE_NOT_FOUND');});
t('direct Floating Island Grid resolves to semantic location and asset route',()=>{const r=loc.resolveLocationFromGrid(base,760);assert.equal(r.status,'RESOLVED');assert.deepEqual(r.locationRef,loc.locationRefFloatingIsland(1540000147));assert.equal(r.directRootRoute.gridDataPath,'GridData/FloatingIslands/FloatingIsland_Urban/FloatingIsland_UrbanGrid-GridData.json');assert.equal(r.sourceDiagnostics.directRootGridId,760);assert.equal(r.sourceDiagnostics.subGridDepth,0);});
t('nested SubGrid resolves to parent Floating Island without exposing child GridID as identity',()=>{const p=profileFromAudit();p.World.GridCollection.Grids['999001']={ID:999001,GridDataPath:'GridData/Furniture/Test/Child.json',TessellationFactor:2,Objects:{}};p.World.GridCollection.Grids['760'].Objects={'42':{ID:42,ItemID:40000001,X:0,Y:0,Orientation:'GridOrientation_Up',State:{SubGrid:{GridID:999001,DesignID:null}}}};const r=loc.resolveLocationFromGrid(p,999001);assert.equal(r.status,'RESOLVED');assert.deepEqual(r.locationRef,loc.locationRefFloatingIsland(1540000147));assert.equal(r.directRootRoute.gridDataPath,p.World.GridCollection.Grids['760'].GridDataPath);assert.equal(r.sourceDiagnostics.sourceGridId,999001);assert.equal(r.sourceDiagnostics.directRootGridId,760);assert.equal(r.sourceDiagnostics.subGridDepth,1);assert.equal('gridId' in r.locationRef,false);});
t('SubGrid referenced from two semantic owners fails closed',()=>{const p=profileFromAudit();p.World.GridCollection.Grids['999002']={ID:999002,GridDataPath:'GridData/Furniture/Test/AmbiguousChild.json',TessellationFactor:2,Objects:{}};for(const gid of [760,765])p.World.GridCollection.Grids[String(gid)].Objects={'1':{ID:1,ItemID:40000001,X:0,Y:0,Orientation:'GridOrientation_Up',State:{SubGrid:{GridID:999002,DesignID:null}}}};const r=loc.resolveLocationFromGrid(p,999002);assert.equal(r.status,'AMBIGUOUS_FAIL_CLOSED');assert.equal(r.blockers[0].code,'OUTDOOR_LOCATION_AMBIGUOUS');});
t('unowned Grid remains unresolved',()=>{const p=profileFromAudit();p.World.GridCollection.Grids['999003']={ID:999003,GridDataPath:'GridData/Other/Unowned.json',TessellationFactor:2,Objects:{}};const r=loc.resolveLocationFromGrid(p,999003);assert.equal(r.status,'NOT_FOUND');assert.equal(r.blockers[0].code,'OUTDOOR_LOCATION_NOT_FOUND');});
t('Biome LocationRef uses current project tuple and destination GridID is resolved locally',()=>{const p=profileFromAudit();p.World.Villages=[{SceneItemId:1540000004,Areas:{'3':{GridIDs:[7001],Unlocked:true}}}];p.World.GridCollection.Grids['7001']={ID:7001,GridDataPath:'GridData/Villages/Village04-UrbanLevel-GridData.json',TessellationFactor:2,Objects:{}};const ref=loc.locationRefBiome(1540000004,3);const x=loc.resolveLocationRef(p,ref);assert.equal(x.status,'RESOLVED');assert.deepEqual(x.locationRef,ref);const y=loc.resolveLocationFromGrid(p,7001);assert.equal(y.status,'RESOLVED');assert.deepEqual(y.locationRef,ref);});
t('all resolver results preserve persistent write disable',()=>{const a=loc.resolveFloatingIsland(base,1540000147),b=loc.resolveLocationFromGrid(base,760),c=loc.resolveDestinationDirectRoot(base,a.locationRef,{codec:loc.DIRECT_GRID_ROUTE_CODEC,gridDataPath:a.directRoots[0].gridDataPath});assert.equal(a.persistentWriteAuthorized,false);assert.equal(b.persistentWriteAuthorized,false);assert.equal(c.persistentWriteAuthorized,false);});
t('FloatingIsland_Library stays unresolved rather than receiving a guessed SceneItemId',()=>{const fake=Object.keys(base.World.FloatingIslands).map(Number).reduce((a,b)=>Math.max(a,b),0)+1;const r=loc.resolveFloatingIsland(base,fake);assert.equal(r.status,'NOT_FOUND');});
console.log(`RESULT ${passed}/${passed} PASS`);
