import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';

import {SafeProfileEditSession} from '../src/lib/ddv/core/save/safe-edit-session.js';
import {
  MUTATION_ADAPTER_CONTRACT,
  STORAGE_FURNITURE_TRANSITION_IDENTITY_POLICY,
  STORAGE_FURNITURE_TRANSITION_TARGET_KIND,
  STRUCTURAL_WRITE_CANDIDATE_CAPABILITY,
  TRANSACTION_PLAN_CONTRACT,
  createVerifiedWriteCandidate,
  verifyWriteCandidate
} from '../src/lib/ddv/core/save/transaction-foundation.js';
import {BuildIdentityKind,PlatformFamily} from '../src/lib/ddv/core/save/versioning.js';

const encoder=new TextEncoder(),decoder=new TextDecoder();
const ITEM=40001000,CONTAINER=21,LIST=2,BID='52BD625D9B4E0053';
const SWITCH_TARGET=Object.freeze({platform:PlatformFamily.Switch,kind:BuildIdentityKind.SwitchBid,value:BID});
const OWNER='01B CORE - World / Grid / Buildings';
const ADAPTER_ID='01b-storage-transition-v125-v1';
const REF_CONTRACT='ddv.storage-active-reference-index@1';
const TEMPLATE_CONTRACT='ddv.storage-grid-object-template-evidence@1';

function storageObject(){return {ID:42,ItemID:ITEM,X:10,Y:20,Orientation:'GridOrientation_Up',State:{Storage:{ContainerInventoryID:CONTAINER,DefaultContainerInventoryData:'ContainerInventory/Storage/Large',UnlockKeyItemID:0,UnlockLocId:'',DesignID:null}},OpaqueObjectField:{preserve:'exact'}};}
function profile({placed=true,amount=2}={}){return {GameInfo:{InitialVersion:518,Version:624,LastSaveDeviceInfo:{deviceType:'DeviceType_Switch'},Opaque:{keep:true}},Player:{ContainerInventories:{'21':{ID:21,Size:48,Inventory:[{ItemID:30000001,Amount:10,ItemState:null},{ItemID:30000002,Amount:2,ItemState:{Custom:'keep'}}],BelongsToPlayer:true,BlockMoveTo:false,ParentItemID:ITEM,ExtraSize:0,OpaqueContainer:{keep:true}}},NextContainerInventoryID:100,ListInventories:{'2':{ID:2,CompatibleItemType:'ItemType_Furniture',Inventory:{[String(ITEM)]:{Amount:amount,Marker:'None'}},OpaqueList:{keep:true}}},OpaquePlayer:{keep:true}},World:{GridCollection:{Grids:{'3':{ID:3,NextGridObjectID:100,Objects:placed?{'42':storageObject()}:{}},'7':{ID:7,NextGridObjectID:80,Objects:{'9':{ID:9,ItemID:40000001,X:1,Y:1,Orientation:'GridOrientation_Up',State:null}}}}},PlayerHouses:[{HouseItemID:20500005,Floors:[]}],QuestInfo:{keep:'exact'},ConditionalEventHistoryData:{keep:'exact'},OpaqueWorld:{keep:true}}};}
function codec(){return {contract:'p1g-v0',async loadProfile(input){const text=decoder.decode(input);return {inputType:'plain',jsonText:text,metadata:{version:JSON.parse(text).GameInfo.Version}};},parseProfileText(text){return {metadata:{version:JSON.parse(text).GameInfo.Version}};},async createEncodedProfile(text){return encoder.encode(text);},getProfileVersion(metadata){return metadata.version;}};}
async function open(root){return SafeProfileEditSession.open({sourceBytes:encoder.encode(JSON.stringify(root)),codec:codec(),sourcePlatform:PlatformFamily.Switch});}
function refsPlaced(){return {contract:REF_CONTRACT,status:'COMPLETE_CURRENT_SAVE',containerInventoryId:CONTAINER,references:[{gridId:3,gridObjectId:42,itemId:ITEM}]};}
function refsStored(){return {contract:REF_CONTRACT,status:'COMPLETE_CURRENT_SAVE',containerInventoryId:CONTAINER,references:[]};}
function template(sourceSha256){return {contract:TEMPLATE_CONTRACT,provenance:'SAME_SAVE_HASH_BOUND',sourceSha256,itemId:ITEM,containerInventoryId:CONTAINER,gridObject:storageObject()};}
function commonTarget(mode,refs){return {kind:STORAGE_FURNITURE_TRANSITION_TARGET_KIND,mode,itemId:ITEM,containerInventoryId:CONTAINER,containerParentItemId:ITEM,containerBelongsToPlayer:true,containerSize:48,activeReferenceEvidence:refs};}
function preservation(){return {gridObjectIdentityPolicy:STORAGE_FURNITURE_TRANSITION_IDENTITY_POLICY,arrayPolicy:'PRESERVE_ORDER_AND_LENGTH_OUTSIDE_INTENTIONAL',unknownStatePolicy:'OPAQUE_UNCHANGED_REQUIRED',serializerNormalizationPolicy:'REJECT_SEMANTIC_NORMALIZATION',unknownPathPrefixes:[]};}
async function basePlan(s,{mode,target,allowedChanges,preconditions=[],postconditions=[],intent={}}){const ctx=s.getPreflightContext();return {contract:TRANSACTION_PLAN_CONTRACT,planId:`storage-${mode.toLowerCase()}-001`,semanticOwner:OWNER,capabilityRequired:STRUCTURAL_WRITE_CANDIDATE_CAPABILITY,input:{platform:PlatformFamily.Switch,gameVersion:'1.25.0',profileGameInfoVersion:624,originalFileLength:s.source.length,originalSha256:ctx.saveIdentity.sourceRawSha256,codecContract:ctx.codecContract,targetBuild:{...SWITCH_TARGET}},operation:{id:'WORLD_STORAGE_FURNITURE_TRANSITION_V125',owner:OWNER,kind:mode,structuralCapabilitiesSupported:true,planSupported:true,validationPassed:true,runtimeGate:'PENDING'},target,mutationAdapter:{contract:MUTATION_ADAPTER_CONTRACT,id:ADAPTER_ID,owner:OWNER},preconditions,allowedChanges:allowedChanges.map(path=>({path,classification:'INTENTIONAL'})),forbiddenPathPrefixes:['/GameInfo','/World/PlayerHouses','/World/QuestInfo','/World/ConditionalEventHistoryData'],postconditions,preservation:preservation(),sourceEvidence:[{id:'DDV-STORAGE-CONTAINER-SEMANTICS-V125-V1_0',status:'INTEGRATOR_PROMOTED'}],intent};}
function adapter(apply){return {contract:MUTATION_ADAPTER_CONTRACT,id:ADAPTER_ID,owner:OWNER,apply};}
async function expectCode(promise,code){await assert.rejects(promise,e=>{assert.equal(e.code,code,e?.stack||String(e));return true;});}
function crossTarget(){return {...commonTarget('CROSS_GRID_MOVE',refsPlaced()),sourceGridId:3,sourceGridObjectId:42,destinationGridId:7,destinationGridObjectId:80,destinationNextGridObjectIDBefore:80,destinationNextGridObjectIDAfter:81};}
function putTarget(){return {...commonTarget('PUT_AWAY_NONEMPTY',refsPlaced()),sourceGridId:3,sourceGridObjectId:42,listInventoryId:LIST,listAmountBefore:2,listAmountAfter:3};}
async function replaceTarget(s){return {...commonTarget('REPLACE_NONEMPTY',refsStored()),destinationGridId:7,destinationGridObjectId:80,destinationNextGridObjectIDBefore:80,destinationNextGridObjectIDAfter:81,listInventoryId:LIST,listAmountBefore:3,listAmountAfter:2,gridObjectTemplateEvidence:template(s.getPreflightContext().saveIdentity.sourceRawSha256)};}
const crossPaths=['/World/GridCollection/Grids/3/Objects/42','/World/GridCollection/Grids/7/Objects/80','/World/GridCollection/Grids/7/NextGridObjectID'];
const putPaths=['/World/GridCollection/Grids/3/Objects/42',`/Player/ListInventories/2/Inventory/${ITEM}/Amount`];
const replacePaths=['/World/GridCollection/Grids/7/Objects/80','/World/GridCollection/Grids/7/NextGridObjectID',`/Player/ListInventories/2/Inventory/${ITEM}/Amount`];
function applyCross(draft,{containerId=CONTAINER,extra=null}={}){const source=draft.World.GridCollection.Grids['3'].Objects['42'];delete draft.World.GridCollection.Grids['3'].Objects['42'];const out=structuredClone(source);out.ID=80;out.X=30;out.Y=40;out.Orientation='GridOrientation_Right';out.State.Storage.ContainerInventoryID=containerId;if(extra)extra(out,draft);draft.World.GridCollection.Grids['7'].Objects['80']=out;draft.World.GridCollection.Grids['7'].NextGridObjectID=81;}
function applyPut(draft,extra=null){delete draft.World.GridCollection.Grids['3'].Objects['42'];draft.Player.ListInventories['2'].Inventory[String(ITEM)].Amount=3;if(extra)extra(draft);}
function applyReplace(draft,tmpl=storageObject(),extra=null){const out=structuredClone(tmpl);out.ID=80;out.X=30;out.Y=40;out.Orientation='GridOrientation_Right';if(extra)extra(out,draft);draft.World.GridCollection.Grids['7'].Objects['80']=out;draft.World.GridCollection.Grids['7'].NextGridObjectID=81;draft.Player.ListInventories['2'].Inventory[String(ITEM)].Amount=2;}

test('machine contract reuses STRUCTURAL_WRITE_CANDIDATE and freezes storage identity policy',async()=>{const schema=JSON.parse(await readFile(new URL('../contracts/save-transaction-plan.schema.json',import.meta.url),'utf8'));const contract=JSON.parse(await readFile(new URL('../static/ddv/core/save/v1.25/storage-furniture-transition-target-v125.json',import.meta.url),'utf8'));assert.deepEqual(schema.properties.capabilityRequired.enum,['WRITE_CANDIDATE','STRUCTURAL_WRITE_CANDIDATE']);assert.equal(contract.targetKind,STORAGE_FURNITURE_TRANSITION_TARGET_KIND);assert.equal(contract.identityPolicy,STORAGE_FURNITURE_TRANSITION_IDENTITY_POLICY);assert.equal(contract.capability,'STRUCTURAL_WRITE_CANDIDATE');assert.equal(contract.hardFlags.persistentWriteAuthorized,false);assert.equal(contract.hardFlags.PERSISTENT_WRITE,false);});
test('CROSS_GRID_MOVE creates and independently verifies exact declared storage structural delta',async()=>{const s=await open(profile());const plan=await basePlan(s,{mode:'CROSS_GRID_MOVE',target:crossTarget(),allowedChanges:crossPaths});const candidate=await createVerifiedWriteCandidate({session:s,plan,adapter:adapter(d=>applyCross(d))});assert.equal(candidate.manifest.target.kind,STORAGE_FURNITURE_TRANSITION_TARGET_KIND);assert.equal(candidate.manifest.semanticDiff.identityDelta.policy,STORAGE_FURNITURE_TRANSITION_IDENTITY_POLICY);assert.equal(candidate.manifest.verification.gridObjectIdentityPreservation,'DECLARED_STORAGE_TRANSITION_PASS');assert.deepEqual(candidate.manifest.semanticDiff.identityDelta.added.map(x=>x.path),['/World/GridCollection/Grids/7/Objects/80']);assert.deepEqual(candidate.manifest.semanticDiff.identityDelta.removed.map(x=>x.path),['/World/GridCollection/Grids/3/Objects/42']);assert.equal((await verifyWriteCandidate({candidate,codec:codec()})).status,'PASS');});
test('CROSS_GRID_MOVE rejects same-grid mode and non-fresh destination identity',async()=>{const s=await open(profile());const badSame={...crossTarget(),destinationGridId:3};await expectCode(createVerifiedWriteCandidate({session:s,plan:await basePlan(s,{mode:'CROSS_GRID_MOVE',target:badSame,allowedChanges:crossPaths}),adapter:adapter(d=>applyCross(d))}),'TX_STORAGE_CROSS_GRID_DESTINATION_MUST_DIFFER');const badFresh={...crossTarget(),destinationGridObjectId:79};await expectCode(createVerifiedWriteCandidate({session:s,plan:await basePlan(s,{mode:'CROSS_GRID_MOVE',target:badFresh,allowedChanges:crossPaths}),adapter:adapter(d=>applyCross(d))}),'TX_STORAGE_DESTINATION_ID_NOT_EXACT_NEXT');});
test('CROSS_GRID_MOVE rejects destination payload or Storage.ContainerInventoryID drift inside allowed object root',async()=>{const s=await open(profile()),plan=await basePlan(s,{mode:'CROSS_GRID_MOVE',target:crossTarget(),allowedChanges:crossPaths});await expectCode(createVerifiedWriteCandidate({session:s,plan,adapter:adapter(d=>applyCross(d,{extra:o=>{o.OpaqueObjectField={preserve:'changed'};}}))}),'TX_STORAGE_DESTINATION_PAYLOAD_MISMATCH');await expectCode(createVerifiedWriteCandidate({session:s,plan,adapter:adapter(d=>applyCross(d,{containerId:99}))}),'TX_STORAGE_ACTIVE_REFERENCE_STATE_MISMATCH');});
test('PUT_AWAY_NONEMPTY verifies source removal plus existing furniture Amount +1 only',async()=>{const s=await open(profile()),plan=await basePlan(s,{mode:'PUT_AWAY_NONEMPTY',target:putTarget(),allowedChanges:putPaths});const candidate=await createVerifiedWriteCandidate({session:s,plan,adapter:adapter(d=>applyPut(d))});assert.equal(candidate.manifest.verification.gridObjectIdentityPreservation,'DECLARED_STORAGE_TRANSITION_PASS');assert.deepEqual(candidate.manifest.semanticDiff.identityDelta.removed.map(x=>x.path),['/World/GridCollection/Grids/3/Objects/42']);assert.equal((await verifyWriteCandidate({candidate,codec:codec()})).status,'PASS');});
test('PUT_AWAY_NONEMPTY fails closed for empty ContainerInventory',async()=>{const root=profile();root.Player.ContainerInventories['21'].Inventory.forEach(x=>x.Amount=0);const s=await open(root),plan=await basePlan(s,{mode:'PUT_AWAY_NONEMPTY',target:putTarget(),allowedChanges:putPaths});await expectCode(createVerifiedWriteCandidate({session:s,plan,adapter:adapter(d=>applyPut(d))}),'TX_STORAGE_NONEMPTY_CONTAINER_REQUIRED');});
test('ContainerInventories and NextContainerInventoryID cannot be admitted as storage transition paths',async()=>{const s=await open(profile());for(const path of ['/Player/ContainerInventories/21/Inventory/0/Amount','/Player/NextContainerInventoryID']){const plan=await basePlan(s,{mode:'PUT_AWAY_NONEMPTY',target:putTarget(),allowedChanges:[...putPaths,path]});await expectCode(createVerifiedWriteCandidate({session:s,plan,adapter:adapter(d=>applyPut(d))}),'TX_STORAGE_ALLOWED_PATHS_MISMATCH');}});
test('ContainerInventory slot mutation and ListInventory Marker drift are rejected even with structurally valid put-away',async()=>{const s=await open(profile()),plan=await basePlan(s,{mode:'PUT_AWAY_NONEMPTY',target:putTarget(),allowedChanges:putPaths});await expectCode(createVerifiedWriteCandidate({session:s,plan,adapter:adapter(d=>applyPut(d,x=>{x.Player.ContainerInventories['21'].Inventory[0].Amount=9;}))}),'TX_MUTATION_OR_SERIALIZATION_FAILED');await expectCode(createVerifiedWriteCandidate({session:s,plan,adapter:adapter(d=>applyPut(d,x=>{x.Player.ListInventories['2'].Inventory[String(ITEM)].Marker='Changed';}))}),'TX_MUTATION_OR_SERIALIZATION_FAILED');});
test('REPLACE_NONEMPTY verifies hash-bound template, exact selected ContainerInventory and Amount -1',async()=>{const s=await open(profile({placed:false,amount:3})),target=await replaceTarget(s);const plan=await basePlan(s,{mode:'REPLACE_NONEMPTY',target,allowedChanges:replacePaths});const candidate=await createVerifiedWriteCandidate({session:s,plan,adapter:adapter(d=>applyReplace(d,target.gridObjectTemplateEvidence.gridObject))});assert.deepEqual(candidate.manifest.semanticDiff.identityDelta.added.map(x=>x.path),['/World/GridCollection/Grids/7/Objects/80']);assert.equal((await verifyWriteCandidate({candidate,codec:codec()})).status,'PASS');});
test('REPLACE_NONEMPTY rejects active/incomplete reference evidence and wrong same-save template hash',async()=>{const s=await open(profile({placed:false,amount:3})),good=await replaceTarget(s);const active={...good,activeReferenceEvidence:refsPlaced()};await expectCode(createVerifiedWriteCandidate({session:s,plan:await basePlan(s,{mode:'REPLACE_NONEMPTY',target:active,allowedChanges:replacePaths}),adapter:adapter(d=>applyReplace(d,good.gridObjectTemplateEvidence.gridObject))}),'TX_STORAGE_ACTIVE_REFERENCE_DECLARATION_MISMATCH');const incomplete={...good,activeReferenceEvidence:{...refsStored(),status:'UNKNOWN'}};await expectCode(createVerifiedWriteCandidate({session:s,plan:await basePlan(s,{mode:'REPLACE_NONEMPTY',target:incomplete,allowedChanges:replacePaths}),adapter:adapter(d=>applyReplace(d,good.gridObjectTemplateEvidence.gridObject))}),'TX_STORAGE_COMPLETE_ACTIVE_REFERENCE_EVIDENCE_REQUIRED');const wrongHash={...good,gridObjectTemplateEvidence:{...good.gridObjectTemplateEvidence,sourceSha256:'0'.repeat(64)}};await expectCode(createVerifiedWriteCandidate({session:s,plan:await basePlan(s,{mode:'REPLACE_NONEMPTY',target:wrongHash,allowedChanges:replacePaths}),adapter:adapter(d=>applyReplace(d,good.gridObjectTemplateEvidence.gridObject))}),'TX_STORAGE_TEMPLATE_SOURCE_HASH_MISMATCH');});
test('REPLACE_NONEMPTY independently rejects destination payload divergence hidden inside allowed object-add root',async()=>{const s=await open(profile({placed:false,amount:3})),target=await replaceTarget(s),plan=await basePlan(s,{mode:'REPLACE_NONEMPTY',target,allowedChanges:replacePaths});await expectCode(createVerifiedWriteCandidate({session:s,plan,adapter:adapter(d=>applyReplace(d,target.gridObjectTemplateEvidence.gridObject,o=>{o.State.Storage.DefaultContainerInventoryData='changed';}))}),'TX_STORAGE_DESTINATION_PAYLOAD_MISMATCH');});
test('storage target is Switch v1.25 BID/schema exact and never inferred to Steam',async()=>{const s=await open(profile()),plan=await basePlan(s,{mode:'PUT_AWAY_NONEMPTY',target:putTarget(),allowedChanges:putPaths});plan.input.platform=PlatformFamily.SteamWindows;plan.input.targetBuild={platform:PlatformFamily.SteamWindows,kind:BuildIdentityKind.SteamFullVersion,value:'releases_1.25-test'};await expectCode(createVerifiedWriteCandidate({session:s,plan,adapter:adapter(d=>applyPut(d))}),'TX_STORAGE_EXACT_SWITCH_V125_SOURCE_REQUIRED');});
