import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import fs from 'node:fs';

const url=new URL('../static/ddv/core/world/v1.25/scrooge-store-state-v125.json',import.meta.url);
const raw=fs.readFileSync(url,'utf8');
const c=JSON.parse(raw);
assert.equal(c.schema,'ddv.scrooge-store-state@1');
assert.equal(c.artifactId,'DDV-SCROOGE-STORE-STATE-V125-V1_12');
assert.equal(c.status,'PROMOTED');
assert.equal(c.target.platform,'Nintendo Switch');
assert.equal(c.target.gameVersion,'1.25.0');
assert.equal(c.target.buildId,'52BD625D9B4E0053');
assert.equal(c.target.profileSchemaVersion,624);
assert.equal(c.collectionBoundary.authoritativeStoreCollection,'ProfileWorld.Stores');
assert.equal(c.collectionBoundary.distinctCollection,'ProfileWorld.Shops');
assert.equal(c.identity.selectedWorldObjectKey,'GridObject.ItemID');
assert.equal(c.identity.serializedStoreKey,'StoreInfo.BuildingItemID');
assert.equal(c.identity.crossWorldMergeAllowed,false);
assert.deepEqual(c.serializedModel.StoreInfo,['BuildingItemID','Displays','LastRefresh','WeightedItems','CurrentSequenceIndexPerUpgrade']);
assert.deepEqual(c.serializedModel.StoreDisplay,['DisplayItemID','DisplayInfo']);
assert.deepEqual(c.serializedModel.DisplayInfo,['Slots','LayoutType','LastRefresh']);
assert.deepEqual(c.serializedModel.DisplaySlot,['Item','IsAvailable','CurrencyId']);
assert.equal(c.serializedModel.price.serializedSlotField,false);
assert.deepEqual(c.readAddress.tuple,['BuildingItemID','DisplayIndex','SlotIndex']);
assert.equal(c.writerBoundary.persistentWriteAuthorized,false);
assert.equal(c.writerBoundary.WORLD_PERSISTENT_WRITE_V125,false);
for (const x of ['persistent Store slot mutation','purchase replay','restock/refresh generation','Premium Shop mutation','Moonstones mutation','receipt mutation','Premium/DLC entitlement mutation','Apply']) assert.ok(c.writerBoundary.prohibitedActions.includes(x));
assert.equal(c.wepActivation.mutationHandlerAuthorized,false);
assert.equal(c.unresolved.generatorEquivalentRestock,'NOT_PROMOTED');
assert.equal(c.unresolved.persistentManualSlotWriter,'NOT_PROMOTED');
assert.equal(createHash('sha256').update(raw).digest('hex'),'322cd1768a5a75fa8ceea60a0ed7dd65d048666849067ed5ab034a483c60c578');
console.log('PASS ddv.scrooge-store-state@1 v1.12');
