import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const world=require('../static/ddv/core/world/v1.25/adapter-v125.cjs');
const fx=JSON.parse(fs.readFileSync(new URL('./fixtures/ddv-world/core-world-v125-observed-fixture.json',import.meta.url),'utf8'));
const roleAuthority=JSON.parse(fs.readFileSync(new URL('../static/ddv/core/world/v1.25/grid-role-authority-v125.json',import.meta.url),'utf8'));
const source={gameVersion:'1.25.0',platform:'Nintendo Switch',buildIdentity:'52BD625D9B4E0053',profileSchemaVersion:624};
const adapter=world.createAdapter({geometryIndex:fx.geometryIndex,scopeIndex:fx.scopeIndex,gridDataDimensions:fx.gridDataDimensions,gridRoleIndex:roleAuthority});
let passed=0;const t=(name,fn)=>{fn();passed++;console.log('PASS',name);};
const load=(areaId,rootGridId)=>adapter.loadAreaGrid(fx.profile,{villageIndex:0,areaId,rootGridId,source});
t('rejects non-current version',()=>assert.throws(()=>adapter.loadAreaGrid(fx.profile,{villageIndex:0,areaId:7,rootGridId:0,source:{...source,gameVersion:'1.24.13'}}),/WORLD_VERSION_UNSUPPORTED/));
t('ordinary furniture resolves editable in approved static scope',()=>{const o=load(7,0).objects.find(x=>x.itemId===40004907);assert.equal(o.editability,'editable');assert.equal(o.metadata.geometryStatus,'RESOLVED');});
t('Road/Fence stays delegated to 01C',()=>{const o=load(7,0).objects.find(x=>x.itemId===40100014);assert.equal(o.editability,'readonly');assert.ok(o.metadata.reasons.includes('ROAD_FENCE_DELEGATED_01C'));});
t('HouseData is readonly without inferring PlayerHouse from index',()=>{const o=load(7,0).objects.find(x=>x.itemId===20000036);assert.equal(o.editability,'readonly');assert.ok(o.metadata.reasons.includes('HOUSE_DATA_READ_ONLY'));});
t('serialized SubGrid remains local portable state',()=>{const o=load(3,5).objects.find(x=>x.itemId===40003102);assert.equal(o.portableState.codec,'subgrid.serialized-local-child@1');assert.equal(o.portableState.child.width,6);assert.equal(o.portableState.child.height,6);});
t('explicit Village04 alias is accepted only through authority table',()=>{const d=adapter.loadAreaGrid(fx.profile,{villageIndex:0,areaId:7,rootGridId:0,source});assert.equal(d.target.rootGridRole.status,'SINGLE_GRID_EXPLICIT_DERIVED_ALIAS');assert.equal(d.target.rootGridRole.mutationAuthorized,true);});
t('unlisted suffix-looking single-grid path gets no heuristic alias',()=>{const r=world.classifyDirectGridRole({GridDataPath:'GridData/Villages/Fake-GridData.json'},[99],roleAuthority);assert.equal(r.status,'SINGLE_DIRECT_GRID_BASELINE');assert.equal(r.authority,null);});
t('multi-grid unknown root fails closed',()=>{const d=adapter.loadAreaGrid(fx.profile,{villageIndex:0,areaId:99,rootGridId:0,source});assert.equal(d.target.rootGridRole.status,'MULTI_GRID_ROLE_UNKNOWN');assert.equal(d.capabilities.worldDryRunMutation,'unsupported-root-grid-role');});
t('persistent writer remains unsupported',()=>{const d=load(7,0);assert.equal(d.capabilities.worldPersistentWrite,'unsupported');});
console.log(`RESULT ${passed}/${passed} PASS`);
