import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const placement=require('../src/lib/ddv/core/world/placement-v125.js');
const world=require('../src/lib/ddv/core/world/adapter-v125.js');
const fx=JSON.parse(fs.readFileSync(new URL('./fixtures/ddv-world/core-world-v125-observed-fixture.json',import.meta.url),'utf8'));
let passed=0;const t=(name,fn)=>{fn();passed++;console.log('PASS',name);};
function tinyGrid(){return {sizeX:8,sizeY:8,encoding:'DIRECT_FIXED32',floorTypes:Array(64).fill(8),compactedFloorTypeIndex:[],compactedFloorTypes:[]};}
const geom={itemID:9001,concreteType:'FurnitureItemData',sizeX:2,sizeY:2,layers:[68,68,68,68],acceptedFloorTypesFlag:8,strideOverride:null,areaTessellationFactor:1};
const zeroGeom={itemID:9002,concreteType:'FurnitureItemData',sizeX:2,sizeY:2,layers:[0,0,0,68],acceptedFloorTypesFlag:8,strideOverride:null,areaTessellationFactor:1};
const wallGeom={...geom,itemID:9003,acceptedFloorTypesFlag:8|0x800};
const geometryIndex={'9001':geom,'9002':zeroGeom,'9003':wallGeom};

t('current layer collision exclusive low bits',()=>{assert.equal(placement.layersCollide(4,4),true);assert.equal(placement.layersCollide(4,8),false);});
t('current layer collision Clear vs Blocking is symmetric',()=>{assert.equal(placement.layersCollide(0x20,0x40),true);assert.equal(placement.layersCollide(0x40,0x20),true);});
t('unrelated high layer bits do not collide',()=>assert.equal(placement.layersCollide(0x100,0x200),false));
t('cardinal local mapping Up mirrors both axes',()=>assert.deepEqual(placement.cardinalLocalCell(geom,0,0,0,1),{x:1,y:1,index:3}));
t('cardinal local mapping Right matches current GridArea transform',()=>assert.deepEqual(placement.cardinalLocalCell(geom,4,0,0,1),{x:0,y:1,index:1}));
t('valid non-wall cardinal placement passes',()=>{const r=placement.validateOrdinaryCardinalPlacement({gridData:tinyGrid(),geometryIndex,objects:[],candidate:{editorId:'c',itemId:9001,x:2,y:2,orientation:0},gridTessellationFactor:1,excludeEditorId:'c'});assert.equal(r.status,'VALID');});
t('out of bounds is invalid',()=>{const r=placement.validateOrdinaryCardinalPlacement({gridData:tinyGrid(),geometryIndex,objects:[],candidate:{editorId:'c',itemId:9001,x:7,y:7,orientation:0},gridTessellationFactor:1,excludeEditorId:'c'});assert.equal(r.verdict,'INVALID_BOUNDS');});
t('non-cardinal mutation fails closed',()=>{const r=placement.validateOrdinaryCardinalPlacement({gridData:tinyGrid(),geometryIndex,objects:[],candidate:{editorId:'c',itemId:9001,x:2,y:2,orientation:2},gridTessellationFactor:1,excludeEditorId:'c'});assert.equal(r.verdict,'UNSUPPORTED_ORIENTATION');});
t('wall GridArea mutation fails closed',()=>{const r=placement.validateOrdinaryCardinalPlacement({gridData:tinyGrid(),geometryIndex,objects:[],candidate:{editorId:'c',itemId:9003,x:2,y:2,orientation:0},gridTessellationFactor:1,excludeEditorId:'c'});assert.equal(r.verdict,'UNSUPPORTED_WALL_AREA');});
t('zero-layer cells skip floor validation as current native does',()=>{const gd=tinyGrid();gd.floorTypes=[...gd.floorTypes];gd.floorTypes[8*2+2]=0;const r=placement.validateOrdinaryCardinalPlacement({gridData:gd,geometryIndex,objects:[],candidate:{editorId:'c',itemId:9002,x:2,y:2,orientation:8},gridTessellationFactor:1,excludeEditorId:'c'});assert.equal(r.status,'VALID');});
t('nonzero-layer floor mismatch is invalid',()=>{const gd=tinyGrid();gd.floorTypes=[...gd.floorTypes];gd.floorTypes[8*3+3]=0;const r=placement.validateOrdinaryCardinalPlacement({gridData:gd,geometryIndex,objects:[],candidate:{editorId:'c',itemId:9001,x:2,y:2,orientation:8},gridTessellationFactor:1,excludeEditorId:'c'});assert.equal(r.verdict,'INVALID_FLOOR');});
t('occupied cell follows current GridLayers.Collide',()=>{const existing={editorId:'e',itemId:9001,x:2,y:2,orientation:0};const r=placement.validateOrdinaryCardinalPlacement({gridData:tinyGrid(),geometryIndex,objects:[existing],candidate:{editorId:'c',itemId:9001,x:2,y:2,orientation:0},gridTessellationFactor:1,excludeEditorId:'c'});assert.equal(r.verdict,'OCCUPIED');});
t('ClearArea remains unsupported destructive policy',()=>{const r=placement.validateOrdinaryCardinalPlacement({gridData:tinyGrid(),geometryIndex,objects:[],candidate:{editorId:'c',itemId:9001,x:2,y:2,orientation:0},gridTessellationFactor:1,clearArea:true});assert.equal(r.verdict,'UNSUPPORTED_POLICY');});
t('unknown occupancy geometry fails closed',()=>{const r=placement.validateOrdinaryCardinalPlacement({gridData:tinyGrid(),geometryIndex,objects:[{editorId:'u',itemId:9999,x:7,y:7,orientation:0}],candidate:{editorId:'c',itemId:9001,x:2,y:2,orientation:0},gridTessellationFactor:1,excludeEditorId:'c'});assert.equal(r.verdict,'UNKNOWN_OCCUPANCY');});
t('document validator binds by root GridDataPath',()=>{const gridDataIndex={'GridData/Test.json':tinyGrid()},v=placement.createDocumentPlacementValidator({gridDataIndex,geometryIndex});const before={target:{gridDataPath:'GridData/Test.json',tessellationFactor:1},objects:[{editorId:'a',itemId:9001,x:1,y:1,orientation:0}]};const after=structuredClone(before);after.objects[0].x=2;const r=v(before,after,[{editorId:'a',kinds:['MOVE']}]);assert.equal(r.status,'VALID');});

t('candidate-set swap uses final occupancy, not stale original cells',()=>{const objects=[{editorId:'a',itemId:9001,x:3,y:2,orientation:0},{editorId:'b',itemId:9001,x:1,y:2,orientation:0}];const r=placement.validateOrdinaryCardinalCandidateSet({gridData:tinyGrid(),geometryIndex,objects,candidateEditorIds:['a','b'],gridTessellationFactor:1});assert.equal(r.status,'VALID');});
t('candidate-set translated pair validates together',()=>{const objects=[{editorId:'a',itemId:9001,x:4,y:2,orientation:0},{editorId:'b',itemId:9001,x:6,y:2,orientation:0}];const r=placement.validateOrdinaryCardinalCandidateSet({gridData:tinyGrid(),geometryIndex,objects,candidateEditorIds:['a','b'],gridTessellationFactor:1});assert.equal(r.status,'VALID');});
t('candidate-set internal overlap is rejected',()=>{const objects=[{editorId:'a',itemId:9001,x:4,y:2,orientation:0},{editorId:'b',itemId:9001,x:4,y:2,orientation:0}];const r=placement.validateOrdinaryCardinalCandidateSet({gridData:tinyGrid(),geometryIndex,objects,candidateEditorIds:['a','b'],gridTessellationFactor:1});assert.equal(r.status,'INVALID');assert.equal(r.results[0].result.verdict,'OCCUPIED');});
t('document validator validates multi-object MOVE against final candidate set',()=>{const gridDataIndex={'GridData/Test.json':tinyGrid()},v=placement.createDocumentPlacementValidator({gridDataIndex,geometryIndex});const before={target:{gridDataPath:'GridData/Test.json',tessellationFactor:1},objects:[{editorId:'a',itemId:9001,x:1,y:1,orientation:0},{editorId:'b',itemId:9001,x:3,y:1,orientation:0}]};const after=structuredClone(before);after.objects[0].x=3;after.objects[1].x=1;const r=v(before,after,[{editorId:'a',kinds:['MOVE']},{editorId:'b',kinds:['MOVE']}]);assert.equal(r.status,'VALID');});
t('adapter can bind current native placement validator by default',()=>{const source={gameVersion:'1.25.0',platform:'Nintendo Switch',buildIdentity:'52BD625D9B4E0053',profileSchemaVersion:624};const gridDataIndex={'GridData/Villages/Village04-UrbanLevel-GridData.json':{sizeX:148,sizeY:125,encoding:'DIRECT_FIXED32',floorTypes:Array(148*125).fill(8)}};const native=placement.createDocumentPlacementValidator({gridDataIndex,geometryIndex:fx.geometryIndex});const adapter=world.createAdapter({geometryIndex:fx.geometryIndex,scopeIndex:fx.scopeIndex,gridDataDimensions:fx.gridDataDimensions,nativePlacementValidator:native});const before=adapter.loadAreaGrid(fx.profile,{villageIndex:0,areaId:3,rootGridId:5,source}),after=structuredClone(before),o=after.objects.find(x=>x.itemId===40003102);o.x-=2;const plan=adapter.buildDryRunPlan(before,after);assert.equal(plan.status,'VALID');assert.equal(plan.persistentWriteAuthorized,false);});
console.log(`RESULT ${passed}/20 PASS`);
