export const HOME_COPY=Object.freeze({
  en:{products:'Dreamwish Wand products',decorate:'Decorate',decorateDetail:'Discover the pieces, gather your vision, and shape your world.',collection:'Collection',collectionDetail:'Browse items and entities through your Collection workspace.',guide:'Guide',guideDetail:'Quests, Star Paths, Events, Systems and Issues in one curated place.',presets:'Presets',presetsDetail:'Discover, save and reuse Wand Presets and inspect in-game preset boundaries.',gallery:'Gallery',galleryDetail:'Browse and publish noncompetitive creative works.',dreamsnaps:'DreamSnaps',dreamsnapsDetail:'Current competition, results, archive and your DreamSnaps.',qa:'Q&A',qaDetail:'Ask questions, answer others and share practical Tips.'},
  fr:{products:'Produits Dreamwish Wand',decorate:'Décorer',decorateDetail:'Découvrez les éléments, rassemblez votre vision et façonnez votre monde.',collection:'Collection',collectionDetail:'Parcourez objets et entités dans votre espace Collection.',guide:'Guide',guideDetail:'Quêtes, Voies des étoiles, Événements, Systèmes et Problèmes réunis.',presets:'Presets',presetsDetail:'Découvrez, sauvegardez et réutilisez les Presets Wand, avec les limites des presets en jeu.',gallery:'Gallery',galleryDetail:'Explorez et publiez des créations non compétitives.',dreamsnaps:'DreamSnaps',dreamsnapsDetail:'Compétition actuelle, résultats, archive et vos DreamSnaps.',qa:'Q&R',qaDetail:'Posez des questions, répondez et partagez des Astuces.'},
  it:{products:'Prodotti Dreamwish Wand',decorate:'Decora',decorateDetail:'Scopri gli elementi, raccogli la tua visione e dai forma al tuo mondo.',collection:'Collection',collectionDetail:'Esplora oggetti ed entità nel tuo spazio Collection.',guide:'Guide',guideDetail:'Missioni, Percorsi Stellari, Eventi, Sistemi e Problemi in un unico luogo curato.',presets:'Presets',presetsDetail:'Scopri, salva e riutilizza i Preset Wand e consulta i limiti dei preset di gioco.',gallery:'Gallery',galleryDetail:'Esplora e pubblica opere creative non competitive.',dreamsnaps:'DreamSnaps',dreamsnapsDetail:'Competizione corrente, risultati, archivio e i tuoi DreamSnaps.',qa:'Q&A',qaDetail:'Fai domande, rispondi e condividi Suggerimenti pratici.'},
  de:{products:'Dreamwish-Wand-Produkte',decorate:'Dekorieren',decorateDetail:'Entdecke die Stücke, sammle deine Vision und gestalte deine Welt.',collection:'Collection',collectionDetail:'Durchsuche Gegenstände und Entitäten in deinem Collection-Arbeitsbereich.',guide:'Guide',guideDetail:'Quests, Sternenpfade, Events, Systeme und Probleme an einem kuratierten Ort.',presets:'Presets',presetsDetail:'Entdecke, speichere und verwende Wand Presets und prüfe Grenzen von In-Game-Presets.',gallery:'Gallery',galleryDetail:'Entdecke und veröffentliche nichtkompetitive kreative Werke.',dreamsnaps:'DreamSnaps',dreamsnapsDetail:'Aktueller Wettbewerb, Ergebnisse, Archiv und deine DreamSnaps.',qa:'Fragen & Tipps',qaDetail:'Stelle Fragen, antworte anderen und teile praktische Tipps.'},
  'es-ES':{products:'Productos de Dreamwish Wand',decorate:'Decorar',decorateDetail:'Descubre las piezas, reúne tu visión y da forma a tu mundo.',collection:'Collection',collectionDetail:'Explora objetos y entidades en tu espacio Collection.',guide:'Guide',guideDetail:'Misiones, Rutas Estelares, Eventos, Sistemas y Problemas en un lugar curado.',presets:'Presets',presetsDetail:'Descubre, guarda y reutiliza Presets de Wand y consulta los límites de presets del juego.',gallery:'Gallery',galleryDetail:'Explora y publica obras creativas no competitivas.',dreamsnaps:'DreamSnaps',dreamsnapsDetail:'Competición actual, resultados, archivo y tus DreamSnaps.',qa:'Preguntas y consejos',qaDetail:'Haz preguntas, responde y comparte Consejos prácticos.'},
  ja:{products:'Dreamwish Wand のプロダクト',decorate:'Decorate',decorateDetail:'飾り付けのピースを見つけ、イメージを集め、世界を形にする。',collection:'Collection',collectionDetail:'Collectionワークスペースからアイテムやエンティティを探す。',guide:'Guide',guideDetail:'Quests・Star Paths・Events・Systems・Issuesを整理された情報から確認する。',presets:'Presets',presetsDetail:'Wand Presetを発見・保存・再利用し、In-Game Presetsの境界も確認する。',gallery:'Gallery',galleryDetail:'競争ではないクリエイティブ作品を見つけ、公開する。',dreamsnaps:'DreamSnaps',dreamsnapsDetail:'開催中の競争、Results、Archive、My DreamSnapsを扱う。',qa:'Q&A',qaDetail:'質問し、回答し、実用的なTipsを共有する。'},
  'zh-CN':{products:'Dreamwish Wand 产品',decorate:'装饰',decorateDetail:'发现装饰元素，汇集你的构想，并塑造你的世界。',collection:'Collection',collectionDetail:'在 Collection 工作区中浏览物品和实体。',guide:'Guide',guideDetail:'在一个经过整理的空间查看任务、星路、活动、系统和问题。',presets:'Presets',presetsDetail:'发现、保存和复用 Wand Preset，并查看游戏内 Preset 的边界。',gallery:'Gallery',galleryDetail:'浏览并发布非竞赛的创意作品。',dreamsnaps:'DreamSnaps',dreamsnapsDetail:'当前竞赛、结果、档案以及你的 DreamSnaps。',qa:'问答',qaDetail:'提问、回答他人并分享实用技巧。'},
  'pt-BR':{products:'Produtos Dreamwish Wand',decorate:'Decorar',decorateDetail:'Descubra as peças, reúna sua visão e molde o seu mundo.',collection:'Collection',collectionDetail:'Explore itens e entidades no seu espaço Collection.',guide:'Guide',guideDetail:'Missões, Caminhos Estelares, Eventos, Sistemas e Problemas em um espaço curado.',presets:'Presets',presetsDetail:'Descubra, salve e reutilize Presets do Wand e consulte os limites dos presets do jogo.',gallery:'Gallery',galleryDetail:'Explore e publique obras criativas não competitivas.',dreamsnaps:'DreamSnaps',dreamsnapsDetail:'Competição atual, resultados, arquivo e seus DreamSnaps.',qa:'Perguntas e Dicas',qaDetail:'Faça perguntas, responda e compartilhe Dicas práticas.'}
});
export function homeCopy(locale){return HOME_COPY[locale]??HOME_COPY.en;}
